# Generated by Django 4.1.4 on 2022-12-16 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=8192)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WS", "Website"),
                            ("IOS", "Ios"),
                            ("ANDRIOD", "Android"),
                        ],
                        default="WEBSITE",
                        max_length=128,
                    ),
                ),
                (
                    "author_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=8192)),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("AM", "Amelioration"),
                            ("FCN", "Fonctionnalite"),
                            ("BG", "Bogue"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("PH", "Priorite Haute"),
                            ("PM", "Priorite Moyenne"),
                            ("PB", "Priorite Basse"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AF", "A Faire"),
                            ("EC", "En Cours"),
                            ("T", "Terminer"),
                        ],
                        default="A faire",
                        max_length=128,
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("AUTHOR", "Auteur"), ("CONTRIBUTOR", "Contributeur")],
                        max_length=128,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("CLIENT", "Client"), ("DEVELOPPEUR", "Dev")],
                        max_length=128,
                    ),
                ),
                (
                    "projects",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=8192)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "issue_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.issue"
                    ),
                ),
            ],
        ),
    ]
