# Generated by Django 4.1.4 on 2022-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_issue_assignee_user_issue_author_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[
                    ("PH", "Priorite Haute"),
                    ("PM", "Priorite Moyenne"),
                    ("PB", "Priorite Basse"),
                ],
                default="PM",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[("AF", "A Faire"), ("EC", "En Cours"), ("T", "Terminer")],
                default="AF",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[
                    ("AM", "Amelioration"),
                    ("FCN", "Fonctionnalite"),
                    ("BG", "Bogue"),
                ],
                default="BG",
                max_length=128,
            ),
        ),
    ]
