# Generated by Django 4.1.4 on 2022-12-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_issue_priority_alter_issue_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="author_user_id",
            new_name="author_user",
        ),
    ]
