# Generated by Django 4.1.4 on 2022-12-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_rename_author_user_id_project_author_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="permission",
            field=models.CharField(
                choices=[("Auteur", "Author"), ("Contributeur", "Contributor")],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                choices=[("Client", "Client"), ("Développeur", "Dev")],
                default="Client",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Priorité haute", "High Priority"),
                    ("Priorité moyenne", "Medium Priority"),
                    ("Priorité basse", "Low Priority"),
                ],
                default="Priorité moyenne",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("A faire", "To Do"),
                    ("En cours", "Wip"),
                    ("Terminer", "Complete"),
                ],
                default="A faire",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Amélioration", "Improvement"),
                    ("Fonctionnalité", "Feature"),
                    ("Bogue", "Bug"),
                ],
                default="Bogue",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("Front-end", "Frontend"),
                    ("Back-end", "Backtend"),
                    ("Ios", "Ios"),
                    ("Android", "Android"),
                ],
                default="Front-end",
                max_length=128,
            ),
        ),
    ]
