# Generated by Django 4.1.4 on 2022-12-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0005_alter_contributor_permission_alter_contributor_role_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributor",
            name="projects",
        ),
        migrations.AddField(
            model_name="contributor",
            name="projects",
            field=models.ManyToManyField(to="projects.project"),
        ),
    ]
