# Generated by Django 4.1.4 on 2022-12-23 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0006_remove_contributor_projects_contributor_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author_user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_author_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[
                    ("Improvement", "Amelioration"),
                    ("Feature", "Fonctionalite"),
                    ("Bug", "Bogue"),
                ],
                default="Bug",
                max_length=128,
            ),
        ),
    ]
